name:                learning-csv
version:             0.1.0.0
github:              "githubuser/learning-csv"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/learning-csv#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- vector
- cassava
- text
- utf8-string
- word8

library:
  source-dirs: src

executables:
  decode-salaries-exe:
    main:                DecodeSalaries.hs
    source-dirs:         app/decode
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-csv
  decode-salaries-by-name-exe:
    main:                DecodeSalariesByName.hs
    source-dirs:         app/decodebyname
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-csv
  decode-with-specific-fields:
    main:                DecodeWithSpecificFields.hs
    source-dirs:         app/decodewithspecific
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-csv
  minimal-decoding:
    main:                MinimalDecoding.hs
    source-dirs:         app/minimaldecoding
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-csv

tests:
  learning-csv-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-csv
